In [12]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.graph_objects as go

In [13]:
df=sns.load_dataset('tips')

In [14]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [15]:
df.iloc[:,:2]

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [16]:
regression=df[["total_bill","tip"]].dropna()
print(regression)

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [17]:
# plt.figure(figsize=(10,6))
# sns.scatterplot(data=regression, x="total_bill", y="tip")
# plt.show()

In [18]:
#storing a data_Set column as a numpy array
clean_data=df.dropna(subset=["total_bill","tip"])
x=clean_data["total_bill"].to_numpy()
y=clean_data["tip"].to_numpy()
# print(x)
# print(y)

In [19]:
# plt.figure(figsize=(10,6))
# sns.scatterplot(clean_data,x="total_bill",y="tip")
# plt.show()

In [20]:
#calculationg slope of regression equation
x_mean=np.mean(x)
y_mean=np.mean(y)
cov=np.sum((x-x_mean)*(y-y_mean))
d=np.sum((x-x_mean)*(x-x_mean))
print(cov)
print(d)
slope=cov/d
print(slope)

2022.6108959016392
19258.46408319672
0.1050245173843534

In [21]:
#calculating intercept
b=y_mean - slope*x_mean
print(b)

0.9202696135546726

In [22]:
y_p=slope*x+b
fig = go.Figure()
fig.add_trace(go.Scatter(x=x,y=y,mode='markers',name='Actual data',marker=dict(color='skyblue',opacity=0.7,size=8)))
fig.add_trace(go.Scatter(x=x,y=y_p,mode='lines',name='Regression line',line=dict(color='red', width=3)))
fig.update_layout(title="Linear regression on 'tips' data set",xaxis_title="Total Bill",yaxis_title="Tip Amount",template="plotly_white",width=900, height=600)
fig.show()